# **Assignment One (EECS3404 W25)**
*your name: Harsh khandelwal your student number: 219698406\ your yorku email:harsh011@my.yorku.ca*

This assignment is mainly for you to review mathematical background and vectorization-based programming. You have to work individually. Remember to fill in your information (name, student number, email) above.

# What to Submit
Please use this notebook to complete assignment one. You have to run all commands and show the results in this notebook. Download the completed notenook as .ipynb and compress it as a .zip file to submit to eClass. Submit only ONE notebook file that contains all of your answers and code to eClass before the deadline. No late submission will be accepted.

* For all written parts, write your answers in text cells. To avoid confusions in marking, better to embed [latex](https://www.cmor-faculty.rice.edu/~heinken/latex/symbols.pdf) codes to represent all mathematical notations and equations. **No handwriting is accepted.**

* For programming parts, you should give code, comments, explanations and the proper running outputs in both code and text cells. Make your jupyter notebook clean and concise. Remove all unused codes and all intermediate results from the submitted notebook. The submitted notebook should include only the final (best) outputs for each question. Also make sure every code cell runnable so that markers can reproduce the outputs if necessary.

* The usage of generative AI is permitted. Please submit this [form](https://forms.gle/roN8cGjwL1ag25qM9).

### **Q1** (30 marks) **k-NN** ###

**Part 1.1 (10 marks):**
Study [the given sample code](https://colab.research.google.com/drive/15MUPTNbhMoMexwjBMXS6-fARiImbH-LU?usp=sharing), and then modify the code to apply the $k$-NN method to classify the iris data using all provided four features. Show the classification accuracies for different $k$ values.

In [ ]:
# Q1 Part 1.1: k-NN with all four features
# Modify the sample code to use all four features instead of just two

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import numpy as np

# Load iris dataset
iris = load_iris(as_frame=True)

# Use ALL FOUR features (this is the key modification)
X = iris.data  # All 4 features: sepal length, sepal width, petal length, petal width
y = iris.target

# Create training and test sets with stratification
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=0)

print("Dataset Information:")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"Features used: {list(iris.feature_names)}\n")

# Test k-NN with different k values
print("Classification Accuracies for Different k Values:")
print("=" * 50)

for k in range(1, 20):
    # Create and train k-NN classifier
    classifier = KNeighborsClassifier(n_neighbors=k)
    classifier.fit(X_train, y_train)

    # Predict on test set
    y_pred = classifier.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred) * 100
    print(f"k={k:2d}: Accuracy = {accuracy:6.2f}%")

# Find and display the best k value
print("\n" + "=" * 50)
accuracies = {}
for k in range(1, 20):
    classifier = KNeighborsClassifier(n_neighbors=k)
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    accuracies[k] = accuracy_score(y_test, y_pred) * 100

best_k = max(accuracies, key=accuracies.get)
print(f"\nBest k value: {best_k}")
print(f"Best accuracy: {accuracies[best_k]:.2f}%")

Dataset Information:
X_train shape: (112, 4)
X_test shape: (38, 4)
Features used: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Classification Accuracies for Different k Values:
k= 1: Accuracy =  97.37%
k= 2: Accuracy =  94.74%
k= 3: Accuracy = 100.00%
k= 4: Accuracy = 100.00%
k= 5: Accuracy = 100.00%
k= 6: Accuracy = 100.00%
k= 7: Accuracy = 100.00%
k= 8: Accuracy = 100.00%
k= 9: Accuracy = 100.00%
k=10: Accuracy = 100.00%
k=11: Accuracy = 100.00%
k=12: Accuracy = 100.00%
k=13: Accuracy = 100.00%
k=14: Accuracy =  97.37%
k=15: Accuracy = 100.00%
k=16: Accuracy = 100.00%
k=17: Accuracy = 100.00%
k=18: Accuracy = 100.00%
k=19: Accuracy = 100.00%


Best k value: 3
Best accuracy: 100.00%


**Part 1.2 (10 marks)**: Follow the [sample code](https://colab.research.google.com/drive/15MUPTNbhMoMexwjBMXS6-fARiImbH-LU?usp=sharing) and train [K Neighbors Regressor](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html) on the [fetch_california_housing](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html), using the 10 closest neighbors. Evaluate and print the Mean Squared Error on the test set.



In [ ]:
# Q1 Part 1.2: K Neighbors Regressor on California Housing Dataset
# Train KNeighborsRegressor with 10 neighbors and evaluate MSE

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

# Load the California housing dataset
housing = fetch_california_housing(as_frame=True)
X = housing.data  # Features
y = housing.target  # Target (median house value)

# Display dataset information
print("Dataset Information:")
print(f"Number of samples: {X.shape[0]}")
print(f"Number of features: {X.shape[1]}")
print(f"Feature names: {list(housing.feature_names)}\n")

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

print(f"Training set shape: {X_train.shape}")
print(f"Test set shape: {X_test.shape}\n")

# Initialize KNeighborsRegressor with 10 neighbors
regressor = KNeighborsRegressor(n_neighbors=10)

# Train the model
regressor.fit(X_train, y_train)

# Make predictions on test set
y_pred = regressor.predict(X_test)

# Evaluate using Mean Squared Error
mse = mean_squared_error(y_test, y_pred)

print("="*50)
print(f"Mean Squared Error (MSE) on test set: {mse:.4f}")
print("="*50)

Dataset Information:
Number of samples: 20640
Number of features: 8
Feature names: ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

Training set shape: (15480, 8)
Test set shape: (5160, 8)

Mean Squared Error (MSE) on test set: 1.1031


**Part 1.3 (10 marks):** Add a preprocessing step to scale the features using **MinMaxScaler** before training a **KNeighborsRegressor**.

Using the scaled data, train:

* A KNeighborsRegressor with the Euclidean distance metric
* A KNeighborsRegressor with the Manhattan distance metric

For both models, evaluate and print the Mean Squared Error on the test set.

In [ ]:
# write your code for Q1.3 here
# Import necessary libraries
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import MinMaxScaler

# 1. Load the dataset
housing = fetch_california_housing(as_frame=True)
X = housing.data
y = housing.target

# 2. Split the data
# Use random_state=0 to match the split in Part 1.2
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# 3. Preprocessing: Scale features using MinMaxScaler
scaler = MinMaxScaler()

# Fit the scaler on the training data ONLY
scaler.fit(X_train)

# Transform both training and test data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Data scaled using MinMaxScaler.")

# 4. Train Model 1: k-NN with Euclidean Distance
# metric='euclidean' is equivalent to p=2 (Minkowski)
knn_euclidean = KNeighborsRegressor(n_neighbors=10, metric='euclidean')
knn_euclidean.fit(X_train_scaled, y_train)
y_pred_euclidean = knn_euclidean.predict(X_test_scaled)
mse_euclidean = mean_squared_error(y_test, y_pred_euclidean)

# 5. Train Model 2: k-NN with Manhattan Distance
# metric='manhattan' is equivalent to p=1 (Minkowski)
knn_manhattan = KNeighborsRegressor(n_neighbors=10, metric='manhattan')
knn_manhattan.fit(X_train_scaled, y_train)
y_pred_manhattan = knn_manhattan.predict(X_test_scaled)
mse_manhattan = mean_squared_error(y_test, y_pred_manhattan)

# 6. Print Results
print("\n--- Model Evaluation (n_neighbors=10) ---")
print(f"MSE with Euclidean distance: {mse_euclidean:.4f}")
print(f"MSE with Manhattan distance: {mse_manhattan:.4f}")

Data scaled using MinMaxScaler.

--- Model Evaluation (n_neighbors=10) ---
MSE with Euclidean distance: 0.4022
MSE with Manhattan distance: 0.3601


### **Q2** (40 marks) **Vectorized Euclidean Distance Matrix** ###

**Part 2.1 (10 marks):**

Given $x_i \in \mathrm{R}^{n}$ for $i=1,...,m$ and $y_j \in \mathrm{R}^{n}$ for $j=1,...,k$, where:
- $\mathbf{X} = [x_1,x_2,....,x_m]$ so $\mathbf{X} \in \mathrm{R}^{n \times m}$

- $\mathbf{Y} = [y_1,y_2,....,y_k]$ so $\mathbf{Y} \in \mathrm{R}^{n \times k}$

we define $\mathbf{D} \in \mathrm{R}^{m,k}$ with each element defined as:

$d_{i,j}=\|x_i-y_j\|^2$

Complete the following implementation to complete the matrix $\mathbf{D}$

In [ ]:
import numpy as np
import time

# Define the input matrices
X = np.array([[1,2,3,5],
              [5,9,8,6]])  # shape (2, 4) -> 2 features, 4 samples
Y = np.array([[2,0,1],
              [0,4,1]])    # shape (2, 3) -> 2 features, 3 samples

print("X :", X)
print("Y :", Y)

print("X shape:", X.shape)
print("Y shape:", Y.shape)

start_time = time.time()

# Initialize D with shape (m, k) -> (4, 3)
# X.shape[1] is m (columns of X)
# Y.shape[1] is k (columns of Y)
D = np.empty((X.shape[1], Y.shape[1]))

# Loop over each column in X (each sample xi)
for i in range(X.shape[1]):
    xi = X[:, i]
    # Loop over each column in Y (each sample yj)
    for j in range(Y.shape[1]):
        yj = Y[:, j]
        # COMPLETE THE LINE BELOW
        # Calculate squared Euclidean distance: sum of squared differences
        D[i, j] = np.sum((xi - yj)**2)

print("--- %s seconds ---" % (time.time() - start_time))
print("D = \n", D)


X : [[1 2 3 5]
 [5 9 8 6]]
Y : [[2 0 1]
 [0 4 1]]
X shape: (2, 4)
Y shape: (2, 3)
--- 0.0005450248718261719 seconds ---
D = 
 [[26.  2. 16.]
 [81. 29. 65.]
 [65. 25. 53.]
 [45. 29. 41.]]


**Part 2.2 (10 marks):**
1. Show that $d_{i,j}=\sum_{l=1}^n x_{i,l}^2 + \sum_{l=1}^n y_{j,l}^2-2x_i^Ty_j$

2. Verify that the summation $\mathbf{x}_i^T  \mathbf{y}_j$ can be vectorized as the following:
$$
\sum x_i^Ty_j = \mathbf{X}^T\mathbf{Y},
$$

2. Show that each element in the row of the matrix $diag(\mathbf{X}^T\mathbf{X}) \mathbf{1}_{m,k}$ can be expressed as $\sum_{l=1}^n x_{i,l}^2$

where:
- $diag$ is a diagonal matrix (all elements are zeros except those in the diagonal)
- $\mathbf{1}_{m,k}$ is a matrix of ones of dimension $m \times k$


4. Similarly, show that each element in the columns of the matrix $\mathbf{1}_{m,k} diag(\mathbf{Y}^T\mathbf{Y})^T $ can be expressed as $\sum_{l=1}^n y_{j,l}^2$
5. Show that $\mathbf{D}=diag(\mathbf{X}^T\mathbf{X}) \mathbf{1}_{m,k}+\mathbf{1}_{m,k} diag(\mathbf{Y}^T\mathbf{Y})-2\mathbf{X}^T\mathbf{Y}$

Vectorized Derivation of Squared Euclidean Distance1. Scalar ExpansionThe squared Euclidean distance between two vectors $x_i$ and $y_j$ is defined by the sum of squared differences. Expanding the quadratic term $(a - b)^2 = a^2 - 2ab + b^2$ across all components yields:$$d_{i,j} = \sum_{l=1}^{n} (x_{i,l} - y_{j,l})^2 = \sum_{l=1}^{n} x_{i,l}^2 + \sum_{l=1}^{n} y_{j,l}^2 - 2\sum_{l=1}^{n} x_{i,l}y_{j,l}$$Using vector notation where $\|x_i\|^2 = x_i^T x_i$, we simplify this to:$$d_{i,j} = \|x_i\|^2 + \|y_j\|^2 - 2x_i^T y_j$$2. Vectorizing the Dot Product ($2x_i^T y_j$)Let $\mathbf{X}$ and $\mathbf{Y}$ be matrices where columns represent individual data vectors. The matrix product $\mathbf{X}^T \mathbf{Y}$ computes all pairwise dot products simultaneously. Specifically, the entry at $(i, j)$ in the resulting matrix is:$$(\mathbf{X}^T \mathbf{Y})_{i,j} = x_i^T y_j$$3. Vectorizing the Squared Norm of $x$ ($\|x_i\|^2$)To represent the term $\|x_i\|^2$ for every pair $(i, j)$, we use a diagonal matrix of squared norms:$diag(\mathbf{X}^T\mathbf{X})$ extracts the squared norms $\|x_i\|^2$ onto the diagonal.Multiplying by $\mathbf{1}_{m,k}$ (a matrix of ones) broadcasts these values across all $k$ columns.Thus, for every element in row $i$:$$(diag(\mathbf{X}^T\mathbf{X})\mathbf{1}_{m,k})_{i,j} = \|x_i\|^2 = \sum_{l=1}^n x_{i,l}^2$$4. Vectorizing the Squared Norm of $y$ ($\|y_j\|^2$)Similarly, for the $y$ terms, we broadcast the squared norms $\|y_j\|^2$ across all $m$ rows:$diag(\mathbf{Y}^T\mathbf{Y})$ captures the squared norms of each $y_j$.Pre-multiplying by $\mathbf{1}_{m,k}$ ensures that every element in column $j$ contains the norm of $y_j$.$$(1_{m,k} diag(\mathbf{Y}^T\mathbf{Y}))_{i,j} = \|y_j\|^2 = \sum_{l=1}^n y_{j,l}^2$$5. Final Matrix FormBy combining the components from steps 2, 3, and 4, we can express the full distance matrix $\mathbf{D}$ (where $\mathbf{D}_{i,j} = d_{i,j}$) without using any summation loops:$$\mathbf{D} = diag(\mathbf{X}^T\mathbf{X})\mathbf{1}_{m,k} + \mathbf{1}_{m,k}diag(\mathbf{Y}^T\mathbf{Y}) - 2\mathbf{X}^T\mathbf{Y}$$

**Part 2.3 (10 marks):**

Use the result $\mathbf{D}=diag(\mathbf{X}^T\mathbf{X}) \mathbf{1}_{m,k}+\mathbf{1}_{m,k} diag(\mathbf{Y}^T\mathbf{Y})-2\mathbf{X}^T\mathbf{Y}$ to write a vectorized program for better implementation efficiency for the matrix $\mathbf{D}$.

Compare your code with the one in Part 2.1 in terms of running speed.

In [ ]:
import numpy as np
import time

# Define the input matrices
X = np.array([[1,2,3,5],
              [5,9,8,6]])
Y = np.array([[2,0,1],
              [0,4,1]])

n, m = X.shape
n, k = Y.shape

print("X shape:", X.shape)
print("Y shape:", Y.shape)

start_time = time.time()

# 1. Compute term: -2 * X^T * Y
term_cross = -2 * np.dot(X.T, Y)

# 2. Compute term: diag(X^T * X)
# Sum of squares for each column of X. Result shape (m,)
# Reshape to (m, 1) to act as a column vector for broadcasting
term_X = np.sum(X**2, axis=0).reshape(-1, 1)

# 3. Compute term: diag(Y^T * Y)
# Sum of squares for each column of Y. Result shape (k,)
# Reshape to (1, k) to act as a row vector for broadcasting
term_Y = np.sum(Y**2, axis=0).reshape(1, -1)

# 4. Combine terms
# Broadcasting automatically handles the "multiplication by ones matrix" concept
D = term_X + term_Y + term_cross

print("--- %s seconds ---" % (time.time() - start_time))
print(D)

X shape: (2, 4)
Y shape: (2, 3)
--- 0.007108926773071289 seconds ---
[[26  2 16]
 [81 29 65]
 [65 25 53]
 [45 29 41]]


**Part 2.4 (10 marks)**

Using the results from Part 2.2.2 and 2.2.3, optimize further in terms of running time the vectorized implementation of $\mathbf{D}$.

*Hint:* check Figure 4 in numpy documentation about [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html#broadcasting-figure-4).

In [ ]:
import numpy as np
import time

# Define the input matrices
X = np.array([[1,2,3,5],
              [5,9,8,6]])
Y = np.array([[2,0,1],
              [0,4,1]])

n, m = X.shape
n, k = Y.shape

print("X shape:", X.shape)
print("Y shape:", Y.shape)

start_time = time.time()

# 1. Compute the squared L2 norms for each vector in X and Y
# Sum over axis=0 (features) to get a value for each sample
# X**2 is element-wise square
sx = np.sum(X**2, axis=0)  # Shape: (m,)
sy = np.sum(Y**2, axis=0)  # Shape: (k,)

# 2. Compute the cross term (dot product)
# -2 * X.T @ Y -> Shape: (m, k)
d_cross = -2 * np.dot(X.T, Y)

# 3. Use Broadcasting to compute D
# sx[:, np.newaxis] converts shape (m,) -> (m, 1)
# sy[np.newaxis, :] converts shape (k,) -> (1, k) (optional, implicit in broadcasting)
# The addition automatically broadcasts these to (m, k)
D = sx[:, np.newaxis] + sy[np.newaxis, :] + d_cross

print("--- %s seconds ---" % (time.time() - start_time))
print(D)

X shape: (2, 4)
Y shape: (2, 3)
--- 0.0004379749298095703 seconds ---
[[26  2 16]
 [81 29 65]
 [65 25 53]
 [45 29 41]]


### **Q3** (20 marks)  **Gradient Descent** ###

**Part 3.1 (10 marks):**
Given the matrix $\mathbf{A} \in \mathbb{R}^{m \times n}$ and the output vector $\mathbf{y} \in \mathbb{R}^m$, in order to solve the following linear equation:
$$
\mathbf{A} \mathbf{x} = \mathbf{y}
$$
for the input vector $\mathbf{x} \in \mathbb{R}^n$, we may seek to solve the following optimization problem:
$$
\min_{\mathbf{x}}  \big\Vert \mathbf{A} \mathbf{x} - \mathbf{y} \big\Vert^2
$$

Solving this optimization problem is equivallent to solving the original linear equation. Derive a gradient decent algorithm to solve this optimization optimization.

To solve the linear equation $\mathbf{Ax} = \mathbf{y}$, we minimize the objective function $J(\mathbf{x}) = \|\mathbf{Ax} - \mathbf{y}\|^2$,which represents the squared Euclidean norm of the error.
Here is the derivation for the gradient descent algorithm:Define the Objective Function:
 The goal is to minimize the cost function $J(\mathbf{x})$, defined as the squared norm of the residual vector.
 Expand the Objective Function: By applying the property $\|\mathbf{z}\|^2 = \mathbf{z}^T\mathbf{z}$, we expand the expression into a quadratic form:$J(\mathbf{x}) = (\mathbf{Ax} - \mathbf{y})^T(\mathbf{Ax} - \mathbf{y})$$J(\mathbf{x}) = \mathbf{x}^T\mathbf{A}^T\mathbf{Ax} - \mathbf{x}^T\mathbf{A}^T\mathbf{y} - \mathbf{y}^T\mathbf{Ax} + \mathbf{y}^T\mathbf{y}$Because the term $\mathbf{x}^T\mathbf{A}^T\mathbf{y}$ is a scalar, it is equivalent to its transpose $\mathbf{y}^T\mathbf{Ax}$.
 This simplifies the function to $J(\mathbf{x}) = \mathbf{x}^T\mathbf{A}^T\mathbf{Ax} - 2\mathbf{x}^T\mathbf{A}^T\mathbf{y} + \mathbf{y}^T\mathbf{y}$.Compute the Gradient: To find the direction of steepest ascent, we take the gradient of $J(\mathbf{x})$ with respect to $\mathbf{x}$ using matrix calculus identities:$\nabla_{\mathbf{x}}J(\mathbf{x}) = 2\mathbf{A}^T\mathbf{Ax} - 2\mathbf{A}^T\mathbf{y}$Factoring out the shared terms, we get $\nabla_{\mathbf{x}}J(\mathbf{x}) = 2\mathbf{A}^T(\mathbf{Ax} - \mathbf{y})$.Update Rule: The gradient descent algorithm iteratively updates the vector $\mathbf{x}$ by taking steps in the opposite direction of the gradient. Using $\eta$ (eta) as the learning rate, the update rule for iteration $t+1$ is:$\mathbf{x}^{(t+1)} = \mathbf{x}^{(t)} - \eta \nabla_{\mathbf{x}}J(\mathbf{x}^{(t)})$By substituting our derived gradient: $\mathbf{x}^{(t+1)} = \mathbf{x}^{(t)} - \eta \cdot 2\mathbf{A}^T(\mathbf{Ax}^{(t)} - \mathbf{y})$This can be written as: $\mathbf{x}^{(t+1)} = \mathbf{x}^{(t)} - 2\eta\mathbf{A}^T(\mathbf{Ax}^{(t)} - \mathbf{y})$.

**Part 3.2 (10 marks):**  Use `jax.numpy` and its auto-grad function to write a gradient descent code to solve the above optimization problem for the following two cases. For each case,  print the found solution $\mathbf{x}^*$.

In [ ]:
import jax.numpy as jnp

A1 = jnp.array([[ 0.59752613, 0.6905346, -0.50891773, 0.65463308, 0.26701531, -0.56915274, 0.11808333, 0.46735838],
 [-0.89526606, 0.79715922, 0.57452342, -0.00629485, 0.44091118, -0.90772543, 0.34577912, 0.67014199],
 [ 0.93670858, 0.72254387, 0.99337376, 0.21567713, 0.05358001, 0.71163904, -0.8129734, -0.77292358],
 [-0.40845634, 0.74702203, -0.36284625, 0.92230974, 0.98837581, 0.69059759, -0.33978374, 0.59868784],
 [ 0.09642706, -0.43787392, -0.67600912, -0.45671585, 0.56035694, 0.72904483, 0.79505001, -0.29354031],
 [-0.59517708, 0.08172389, 0.38847584, 0.21164882, -0.09421962, -0.6612324, -0.7419197, -0.11201114],
 [-0.90998187, 0.10939955, -0.00644353, -0.50790748, 0.69847656, -0.35544255, -0.78111919, 0.76442594],
 [ 0.0696891, -0.43123797, 0.87752935, -0.53844923, -0.05382915, -0.77473227, 0.37893365, 0.4033205 ]])

y1 = jnp.array([[0.81025244],[0.12633403],[-0.27351843],[-0.22738992],[-0.04246509],[-0.74659567],[0.29532475],[0.29147134]])

print(A1.shape)
print(y1.shape)

(8, 8)
(8, 1)


In [ ]:
import jax.numpy as jnp

A2 = jnp.array([[0.8847363,  0.20735656, 0.3773889,  0.23544965, 0.58455062, 0.60455535],
 [0.22066618, 0.10340076, 0.82985727, 0.51556355, 0.16158017, 0.01554002],
 [0.77804031, 0.53846337, 0.52636412, 0.52573696, 0.05653821, 0.9502298 ],
 [0.28905543, 0.25418091, 0.68436999, 0.36737675, 0.11333675, 0.50065588],
 [0.0923724,  0.40013578, 0.10427759, 0.88367601, 0.04567698, 0.5614461 ],
 [0.76325149, 0.05564603, 0.73700669, 0.78701047, 0.3065009,  0.81391347],
 [0.42297042, 0.06445234, 0.37385898, 0.95497206, 0.98407816, 0.28076653],
 [0.10806804, 0.76714286, 0.82931698, 0.25355806, 0.09899629, 0.47661276],
 [0.55615413, 0.32609653, 0.84413152, 0.73315836, 0.58309715, 0.84786528],
 [0.95206656, 0.1132698,  0.39265378, 0.75970375, 0.08369203, 0.65761839]])

y2 = jnp.array([[0.5806555 ], [0.47827308], [0.61024271], [0.15632305], [0.93126525], [0.91945009], [0.1717938 ],
                [0.92275104], [0.78164574], [0.71781675]])

print(A2.shape)
print(y2.shape)


(10, 6)
(10, 1)


In [ ]:
# for part 3.2, write your code here

import jax.numpy as jnp
from jax import grad

# 1. Define the objective function: J(x) = ||Ax - y||^2
def loss_fn(x, A, y):
    diff = jnp.dot(A, x) - y
    return jnp.sum(diff**2)

# 2. Use JAX to automatically create the gradient function
# grad(loss_fn) creates a function that computes dJ/dx
grad_loss = grad(loss_fn)

# 3. Define the Gradient Descent Solver
def solve_gradient_descent(A, y, learning_rate=0.01, n_iter=5000):
    # n is the number of features (columns in A)
    n = A.shape[1]

    # Initialize x (e.g., with zeros)
    x = jnp.zeros((n, 1))

    # Gradient Descent Loop
    for i in range(n_iter):
        # Calculate gradient using auto-grad
        gradients = grad_loss(x, A, y)

        # Update rule: x = x - learning_rate * gradient
        x = x - learning_rate * gradients

    return x

# --- Solve Case 1 ---
print("--- Solving Case 1 ---")
x1_star = solve_gradient_descent(A1, y1, learning_rate=0.01)
print("Found solution x* for Case 1:\n", x1_star)

# --- Solve Case 2 ---
print("\n--- Solving Case 2 ---")
# Case 2 may require slightly different tuning
x2_star = solve_gradient_descent(A2, y2, learning_rate=0.005)
print("Found solution x* for Case 2:\n", x2_star)

--- Solving Case 1 ---
Found solution x* for Case 1:
 [[ 0.6562772 ]
 [ 0.57104456]
 [-0.37316814]
 [-0.7716162 ]
 [-0.374516  ]
 [ 0.00761168]
 [ 0.02575722]
 [ 0.94208306]]

--- Solving Case 2 ---
Found solution x* for Case 2:
 [[ 0.1740973 ]
 [ 0.5882414 ]
 [ 0.15487368]
 [ 0.46568918]
 [-0.2906931 ]
 [ 0.16031219]]
